### ISSUE TITLE
Error with new changes in Docker container

### ISSUE THREAD

**Issue by vinanrra** [surajcm/darkhold#6]
I'm getting errors with the database creation/migration, I'm not sure but here is the full log:

**[Darkhold_logs.txt](https://github.com/surajcm/darkhold/files/6496104/Darkhold_logs.txt)**

This is repeating multiple times:
```
SQL State  : 42S22
Error Code : 42122
```

The Docker container should be working unless Darkhold need new requirements.

I thought that was a problem with Volume permissions and seems like there is no issue in the Docker image, so seems to be internal (code?).

**Comment by surajcm** [comment]
I guess it is internal, a typo in the SQL caused this issue. I just fixed it and pushed the changes, hope it will clean up the errors. Please check and let me know.

**Comment by vinanrra** [comment]
Now its working without problem.
